language: go

sudo: false

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - tip

before_script:
  - go vet ./...
  - golint ./... 

gobuild_args: -X main.Version $(git rev-parse --short HEAD) 

script:
  - go test -v ./...